services:
  redis:
    image: ariadne26/redis:cve-2016-9086-inited
  postgresql:
    image: ariadne26/postgres:cve-2016-9086-inited
    ports:
    - "0:5432"
    environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    volumes:
    - ./load-extensions.sh:/docker-entrypoint-initdb.d/load-extensions.sh

  gitlab:
    image: ariadne26/gitlab:cve-2016-9086-inited
    depends_on:
    - redis
    - postgresql
    ports:
    - "0:80"
    environment:
    - DEBUG=false
    - GITLAB_PORT=8080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=secret-key-is-here1
    - GITLAB_SECRETS_SECRET_KEY_BASE=secret-key-is-here2
    - GITLAB_SECRETS_OTP_KEY_BASE=secret-key-is-here3
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - REDIS_HOST=redis
    - GITLAB_ROOT_PASSWORD=vulhub123456
