services:
  gitlab14xss:
    #image: gitlab/gitlab-ce:14.1.0-ce.0
    image: gitlab-ce-fast-start:14.1.0
    #container_name: gitlab14
    hostname: "gitlab.local"
    shm_size: "1g"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['initial_root_password'] = 'Password123!'
        gitlab_rails['gitlab_email_enabled'] = false

        postgresql['listen_address'] = "0.0.0.0"
        postgresql['port'] = 5432
        postgresql['trust_auth_cidr_addresses'] = %w(127.0.0.1/24)
        postgresql['md5_auth_cidr_addresses'] = %w(0.0.0.0/0)
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"
        gitlab_rails['db_host'] = "0.0.0.0"
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_database'] = "gitlabhq_production"
    ports:
      - "0:80"

#cat /etc/gitlab/gitlab.rb
# z5DDDf8efs7dH_62qTfi