services:
  cmsms:
    image: ariadne26/cmsms:2.2.9.1-installed
    ports:
     - "0:80"
    depends_on:
     - mysql
    volumes:
     - ./config.php:/var/www/html/config.php
  mysql:
    image: ariadne26/mysql:5.7-cmsms-installed
    ports:
     - "0:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=cmsms
